### PR TITLE
Skill overhaul (part 2, The beginning)

### PR DESCRIPTION
**Pull request by BenDawgAK**
See issue #10

### CODE REVIEW

**Comment by CoconutMacaroon** [comment]
Can I reformat this as a table before we merge it?

**Comment by BenDawgAK** [comment]
Oh yeah sure!

**Comment by CoconutMacaroon** [comment]
It won't let me. Can we merge it, and then I change it?

**Comment by BenDawgAK** [comment]
Sure. create a new issue before you do that though

**Pull request merged**
