### PR TITLE
Convert skill keywords to table

### PR DESCRIPTION
**Pull request by CoconutMacaroon**

### CODE REVIEW

**Comment by CoconutMacaroon** [comment]
I am wondering: @tofu99 @BenDawgAK Should Aim/Archery be part of `Ranged`? Or can they be separate, and it would be (if you were shooting a bow and arrow) `aim + archery + ranged`? I would prefer the latter, as it adds more options, but I don't have a strong preference.

**Comment by BenDawgAK** [comment]
Archery is a skill, Ranged is a descriptor.

**Comment by CoconutMacaroon** [comment]
Wait. What is a descriptor???

**Comment by BenDawgAK** [comment]
keywords sorry

**Comment by CoconutMacaroon** [comment]
So skills have modifiers, and keywords are just categories?

**Comment by BenDawgAK** [comment]
Keywords are the modifiers

**Comment by CoconutMacaroon** [comment]
OK... so if keywords are modifiers, then what are skills?

**Comment by BenDawgAK** [comment]
skills are the things you roll, keywords are just the modifiers

**Comment by CoconutMacaroon** [comment]
So, if I was trying to shoot a bow, a skill would set the DC, and a keyword would let me re-roll dice?

**Comment by BenDawgAK** [comment]
a skill would be the reroll, keywords are just reference for injuries or flavor

**Comment by BenDawgAK** [comment]
so if a player wanted to attack, they would use a skill marked as combat

**Comment by CoconutMacaroon** [comment]
I get that. But how would you "use the skill"? Does the skill set the DC or give a re-roll bonus? Or is it just there as a type of action/a category?

**Comment by BenDawgAK** [comment]
skills give the reroll bonus, the gm sets the DC

**Comment by CoconutMacaroon** [comment]
So, to clarify, skills let you re-roll the dice. The DM sets the DC. So keywords set what type of action you are trying to do?

**Comment by BenDawgAK** [comment]
more or less yeah

**Comment by CoconutMacaroon** [comment]
Then can we remove `Ranged` and `Melee` from the keyword list?

**Comment by CoconutMacaroon** [comment]
And thanks so much for explaining this to me.

**Comment by BenDawgAK** [comment]
keep ranged and melee.

**Comment by BenDawgAK** [comment]
yep!

**Pull request merged**
